name: Verify Project

on:
  release:
    types: [ created ]

env:
  TEST_REPO: project-tests
  MAIN_PATH: 'project/SearchEngine'
  TEST_PATH: 'test/SearchEngineTest'

jobs:
  build:
    name: Verify Project
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
